#!/bin/sh
set -e

if [ -x "/etc/init.d/libera-dummy" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d libera-dummy stop || exit $?
	else
		/etc/init.d/libera-dummy stop || exit $?
	fi
fi
